---
- name: Simple OpenStack Deployment Example
  hosts: localhost
  gather_facts: False
  vars:
    instance_name: cirros
    image_name: cirros-0.5.1-x86_64
    network_id: 515c7188-1091-4d9e-a43b-ab2c6a4401a6
    flavor_name: small
    key_name: demo
    group: webservers
  
  tasks:
  - name: Launch OpenStack Instance
    openstack.cloud.server:
      state: present
      name: "{{ instance_name }}"
      image: "{{ image_name }}"
      key_name: "{{ key_name }}"
      timeout: 200
      flavor: "{{ flavor_name }}"
      nics:
        - net-id: "{{ network_id }}"
      meta:
        hostname: "{{ instance_name }}.openstacklocal"
        group: "{{ group_name }}"
    register: instance

  - name: Print instance information
    debug:
      var: instance
    
