---
- name: Simple OpenStack Deployment Example Teardown
  hosts: localhost
  gather_facts: False
  vars:
    instance_name: cirros
    image_name: cirros-0.5.1-x86_64
    network_id: 515c7188-1091-4d9e-a43b-ab2c6a4401a6
    flavor_name: small
    key_name: demo
  
  tasks:
  - name: Terminate OpenStack Instance
    openstack.cloud.server:
      state: absent
      name: "{{ instance_name }}" 
      timeout: 300
